USE [master]
GO

/****** Object:  Database [GrupoEmpresarial]    Script Date: 30/01/2024 15:39:32 ******/
CREATE DATABASE [GrupoEmpresarial]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GrupoEmpresarial', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.BASEPADRAO\MSSQL\DATA\GrupoEmpresarial.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GrupoEmpresarial_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.BASEPADRAO\MSSQL\DATA\GrupoEmpresarial_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GrupoEmpresarial].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GrupoEmpresarial] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET ARITHABORT OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GrupoEmpresarial] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GrupoEmpresarial] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GrupoEmpresarial] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GrupoEmpresarial] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GrupoEmpresarial] SET  MULTI_USER 
GO

ALTER DATABASE [GrupoEmpresarial] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GrupoEmpresarial] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GrupoEmpresarial] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GrupoEmpresarial] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GrupoEmpresarial] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GrupoEmpresarial] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GrupoEmpresarial] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GrupoEmpresarial] SET  READ_WRITE 
GO


